# Generated by Django 6.1 on 2026-09-05 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('region', models.CharField(max_length=100)),
                ('contact_status', models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('do_not_contact', 'Do Not Contact')], default='not_yet_contacted', max_length=20)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('public_phone', models.CharField(blank=True, max_length=30)),
                ('source_url', models.URLField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('public_phone', models.CharField(blank=True, max_length=30)),
                ('website_url', models.URLField(blank=True)),
                ('contact_status', models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('do_not_contact', 'Do Not Contact')], default='not_yet_contacted', max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='outreach.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255)),
                ('club_type', models.CharField(blank=True, max_length=100)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('public_phone', models.CharField(blank=True, max_length=30)),
                ('contact_status', models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('do_not_contact', 'Do Not Contact')], default='not_yet_contacted', max_length=20)),
                ('supported_by_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supported_clubs', to='outreach.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('source_url', models.URLField(blank=True)),
                ('last_verified', models.DateField(blank=True, null=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'outreach'), ('model', 'bank')), models.Q(('app_label', 'outreach'), ('model', 'branch')), models.Q(('app_label', 'outreach'), ('model', 'club')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='outreach_co_content_4d36a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('do_not_contact', 'Do Not Contact')], default='not_yet_contacted', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_contacted', models.DateTimeField(blank=True, null=True)),
                ('outreach_method', models.CharField(blank=True, max_length=50)),
                ('draft_email', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'outreach'), ('model', 'bank')), models.Q(('app_label', 'outreach'), ('model', 'branch')), models.Q(('app_label', 'outreach'), ('model', 'club')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='outreach_op_content_7aa112_idx')],
            },
        ),
    ]
