# Generated by Django 6.1 on 2026-09-12 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_alter_branch_options_alter_opportunity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='supported_by_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supported_clubs', to='outreach.branch'),
        ),
    ]
