# Generated by Django 6.1 on 2026-09-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('outreach', '0004_normalize_organisation_contact_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='contact_status',
            field=models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted')], default='not_yet_contacted', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='contact_status',
            field=models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted')], default='not_yet_contacted', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='contact_status',
            field=models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted')], default='not_yet_contacted', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.CheckConstraint(condition=models.Q(('contact_status__in', ('not_yet_contacted', 'contacted'))), name='bank_valid_contact_status'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(('contact_status__in', ('not_yet_contacted', 'contacted'))), name='branch_valid_contact_status'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.CheckConstraint(condition=models.Q(('contact_status__in', ('not_yet_contacted', 'contacted'))), name='club_valid_contact_status'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('not_yet_contacted', 'contacted', 'interested', 'not_interested', 'do_not_contact'))), name='opportunity_valid_status'),
        ),
    ]
