# Generated by Django 6.1 on 2026-09-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0005_separate_organisation_and_opportunity_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bank',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bank',
            name='suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
