# Generated by Django 6.1 on 2026-09-27 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0007_bank_created_by_bank_organisation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='organisation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
