# Generated by Django 6.1 on 2026-09-27 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0008_alter_bank_organisation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='organisation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='organisation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
