# Generated by Django 6.1 on 2026-10-01 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0010_bank_duplicate_override_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('outreach_purpose', models.CharField(max_length=255)),
                ('template_version', models.CharField(default='v1', max_length=50)),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('timed_out', 'Timed Out')], default='pending', max_length=20)),
                ('trigger_source', models.CharField(default='manual', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('regeneration_attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_drafts', to='outreach.opportunity')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_email_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('generate_emaildraft', 'Can generate email draft')],
            },
        ),
    ]
