# Generated by Django 6.1 on 2026-10-04 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0012_emailgenerationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(default='v1', max_length=50)),
                ('purpose', models.CharField(max_length=255)),
                ('template_body', models.TextField()),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_role', models.CharField(blank=True, max_length=150)),
                ('project_details', models.TextField(blank=True)),
                ('call_to_action', models.TextField()),
                ('signature', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_drafts', to='outreach.emailtemplate'),
        ),
    ]
