# Generated by Django 6.1 on 2026-10-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0013_emailtemplate_emaildraft_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgenerationlog',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='emailgenerationlog',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailgenerationlog',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailgenerationlog',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
