# Generated by Django 6.1 on 2026-10-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0014_emailgenerationlog_attempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='is_incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='validation_issues',
            field=models.TextField(blank=True),
        ),
    ]
