# Generated by Django 6.1 on 2026-10-04 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0015_emaildraft_is_incomplete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgenerationlog',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_logs', to='outreach.emaildraft'),
        ),
        migrations.AddField(
            model_name='emailgenerationlog',
            name='template_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
