# Generated by Django 6.1 on 2026-10-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0016_emailgenerationlog_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildraft',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('needs_approving', 'Needs Approving'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent')], default='draft', max_length=20),
        ),
    ]
