# Generated by Django 6.1 on 2026-10-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0017_alter_emaildraft_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
