# Generated by Django 6.1 on 2026-10-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0018_emaildraft_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='contact_status',
            field=models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('do_not_contact', 'Do Not Contact')], default='not_yet_contacted', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='contact_status',
            field=models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('do_not_contact', 'Do Not Contact')], default='not_yet_contacted', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='contact_status',
            field=models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('do_not_contact', 'Do Not Contact')], default='not_yet_contacted', max_length=20),
        ),
    ]
