# Generated by Django 6.1 on 2026-10-05 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0019_alter_bank_contact_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bank',
            name='bank_valid_contact_status',
        ),
        migrations.RemoveConstraint(
            model_name='branch',
            name='branch_valid_contact_status',
        ),
        migrations.RemoveConstraint(
            model_name='club',
            name='club_valid_contact_status',
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.CheckConstraint(condition=models.Q(('contact_status__in', ('not_yet_contacted', 'contacted', 'interested', 'not_interested', 'do_not_contact'))), name='bank_valid_contact_status'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(('contact_status__in', ('not_yet_contacted', 'contacted', 'interested', 'not_interested', 'do_not_contact'))), name='branch_valid_contact_status'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.CheckConstraint(condition=models.Q(('contact_status__in', ('not_yet_contacted', 'contacted', 'interested', 'not_interested', 'do_not_contact'))), name='club_valid_contact_status'),
        ),
    ]
