# Generated by Django 6.1 on 2026-10-06 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0020_remove_bank_bank_valid_contact_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bank',
            name='bank_valid_contact_status',
        ),
        migrations.RemoveConstraint(
            model_name='branch',
            name='branch_valid_contact_status',
        ),
        migrations.RemoveConstraint(
            model_name='club',
            name='club_valid_contact_status',
        ),
        migrations.AlterField(
            model_name='bank',
            name='contact_status',
            field=models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted')], default='not_yet_contacted', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='contact_status',
            field=models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted')], default='not_yet_contacted', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='contact_status',
            field=models.CharField(choices=[('not_yet_contacted', 'Not Yet Contacted'), ('contacted', 'Contacted')], default='not_yet_contacted', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='bank',
            constraint=models.CheckConstraint(condition=models.Q(('contact_status__in', ('not_yet_contacted', 'contacted'))), name='bank_valid_contact_status'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(('contact_status__in', ('not_yet_contacted', 'contacted'))), name='branch_valid_contact_status'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.CheckConstraint(condition=models.Q(('contact_status__in', ('not_yet_contacted', 'contacted'))), name='club_valid_contact_status'),
        ),
    ]
