# Generated by Django 6.1 on 2026-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0021_remove_bank_bank_valid_contact_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='duplicate_override_match',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='duplicate_override_match',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='club',
            name='duplicate_override_match',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
