# Generated by Django 6.1 on 2026-10-07 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0022_bank_duplicate_override_match_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaildraft',
            options={'permissions': [('generate_emaildraft', 'Can generate email draft'), ('approve_emaildraft', 'Can approve email draft'), ('send_emaildraft', 'Can send email draft')]},
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_email_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='approved_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_email_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='send_failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_email_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting Approval'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('sending', 'Sending'), ('sent', 'Sent'), ('send_failed', 'Send Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
