# Generated by Django 6.1 on 2026-10-08 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0025_emaildraft_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDraftHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('submitted', 'Submitted for Approval'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('approval_invalidated', 'Approval Invalidated'), ('withdrawn', 'Withdrawn for Editing'), ('cancelled', 'Cancelled'), ('send_started', 'Send Started'), ('sent', 'Sent'), ('send_failed', 'Send Failed')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField(blank=True)),
                ('recipient_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('subject_snapshot', models.CharField(blank=True, max_length=255)),
                ('body_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='outreach.emaildraft')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_draft_history_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
