# Generated by Django 6.1 on 2026-10-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0026_emaildrafthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildraft',
            name='approver_unavailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='overdue_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='reconciliation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='smtp_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaildrafthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('submitted', 'Submitted for Approval'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('approval_invalidated', 'Approval Invalidated'), ('withdrawn', 'Withdrawn for Editing'), ('cancelled', 'Cancelled'), ('send_started', 'Send Started'), ('sent', 'Sent'), ('send_failed', 'Send Failed'), ('no_approver_available', 'No Approver Available'), ('approval_overdue', 'Approval Overdue'), ('recipient_changed', 'Recipient Email Changed'), ('reconciliation_required', 'Reconciliation Required')], max_length=30),
        ),
    ]
