# Generated by Django 6.1 on 2026-10-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0027_emaildraft_approval_safeguards'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationCreationLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
