# Generated by Django 6.1 on 2026-10-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0028_manual_entry_address_and_creation_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildrafthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('submitted', 'Submitted for Approval'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('approval_invalidated', 'Approval Invalidated'), ('withdrawn', 'Withdrawn for Editing'), ('cancelled', 'Cancelled'), ('send_started', 'Send Started'), ('sent', 'Sent'), ('send_failed', 'Send Failed'), ('no_approver_available', 'No Approver Available'), ('approval_overdue', 'Approval Overdue'), ('recipient_changed', 'Recipient Email Changed'), ('reconciliation_required', 'Reconciliation Required'), ('blocked_do_not_contact', 'Blocked - Do Not Contact')], max_length=30),
        ),
    ]
