# Generated by Django 6.1 on 2026-10-09 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0029_draft_history_blocked_do_not_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_email_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emaildrafthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('submitted', 'Submitted for Approval'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('approval_invalidated', 'Approval Invalidated'), ('withdrawn', 'Withdrawn for Editing'), ('cancelled', 'Cancelled'), ('send_started', 'Send Started'), ('sent', 'Sent'), ('send_failed', 'Send Failed'), ('no_approver_available', 'No Approver Available'), ('approval_overdue', 'Approval Overdue'), ('recipient_changed', 'Recipient Email Changed'), ('reconciliation_required', 'Reconciliation Required'), ('blocked_do_not_contact', 'Blocked - Do Not Contact'), ('reassigned', 'Reassigned')], max_length=30),
        ),
    ]
