# Generated by Django 6.1 on 2026-10-09 02:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('target_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('user_created', 'User created'), ('first_admin_created', 'First Admin created'), ('invitation_sent', 'Invitation sent'), ('invitation_failed', 'Invitation delivery failed'), ('invitation_resent', 'Invitation resent'), ('invitation_accepted', 'Password set from invitation'), ('role_changed', 'Role changed'), ('account_disabled', 'Account disabled'), ('account_enabled', 'Account re-enabled'), ('drafts_reassigned', 'Drafts reassigned')], max_length=30)),
                ('previous_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_performed', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user activities',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
